### PR TITLE
Some Cleanup & prep-work for further updates

### PR DESCRIPTION
**Pull request by commodo**
Tested successfully on Linux/OpenWRT.

Code looks easier for me to grasp/understand like this.

Signed-off-by: Alexandru Ardelean <ardeleanalex@gmail.com>

### CODE REVIEW

**Comment by commodo** [comment]
Re-spinned based on first set of comments:
https://github.com/commodo/lldpd/commit/3653c267b1e360967b9083ff2c7d16f1e3517f30#commitcomment-10544406
https://github.com/commodo/lldpd/commit/2afcdc7fb9fa598e0cd50b8ffb47cdc27ab625ee#commitcomment-10544499

**Comment by commodo** [comment]
So, shall we drop this PR ?
I don't mind if we do; to me this was an exercise in understanding the code.

**Comment by vincentbernat** [comment]
I wanted to release 0.7.14 before merging this. Just in case.

**Comment by commodo** [comment]
Sorry about the double __constructor__.
Thanks for merging :)

**Pull request merged**
