### PR TITLE
Check if there is user defined string before use chassis name for cha…

### PR DESCRIPTION
**Pull request by vic-lin-accton**
Hi Vincent,
    This is for issue #244 opened 20 Sep 2017. Please review it.
Thanks
-Vic

### CODE REVIEW

**Comment by vincentbernat** [comment]
Thanks! This looks good. However, I would like to not add additional command-line options. This should be configurable through lldpcli only. I can fix that this week-end if you want.

**Comment by vic-lin-accton** [comment]
Yes, please fix it. Thanks

**Comment by vic-lin-accton** [comment]
It's not urgent for me. You can fix that when you have time. Thanks

**Comment by vincentbernat** [comment]
I have edited your first commit for small blank changes (space to tab). Other commits enable to use lldpcli to push the change. Let's see if tests go through.

**Comment by vic-lin-accton** [comment]
Great. Thanks

**Comment by vic-lin-accton** [comment]
Override seems to be more correct wording than user defined string for user to configure the chassis id, is it ?

**Comment by vincentbernat** [comment]
Where exactly should "override" be used?

**Comment by vic-lin-accton** [comment]
Sorry, it is in the output of lldpcli  "show config" as below. The code should be in display_configuration()/display.c . I think "description", "platform" are examples, too.

Configuration:
  Transmit delay: 30
........
  Interface pattern for chassis ID: !*
  User defined string for chassis ID: (none)
  Override description with: 
  Override platform with: Linux
  Override system name with: 
  Advertise version: yes

**Comment by vincentbernat** [comment]
I have changed the string to "Override chassis ID with".

**Pull request merged**
