### PR TITLE
Add -Wdocumentation (Clang CFLAG) and fix warning

### PR DESCRIPTION
**Pull request by alagoutte**
Add also -Wheader-guard CLFAG

### CODE REVIEW

**Comment by vincentbernat** [comment]
The warnings with third-party headers are annoying. Is there a way to restrict to a directory?

**Comment by alagoutte** [comment]
Fix upstream ? ;-)

It is possible to use "pragma" for disable for some include

http://stackoverflow.com/questions/20078941/how-to-use-pragma-clang-diagnostics

**Comment by vincentbernat** [comment]
That seems a bit overkill. I gladly take the first two patches but not the last one. Is that OK for you?

**Comment by alagoutte** [comment]
Like you prefer

i have start to work on using pragma on my clang2 branch (no yet fix all include...)
What do you think ? 
May be add some macro ?

**Comment by vincentbernat** [comment]
I'd like not to clutter source with that. It depends how much lines you add. Moreover, currently, there is no real documentation that could be generated from lldpd code.

**Comment by alagoutte** [comment]
I have make the change on clang2 branch ( https://github.com/alagoutte/lldpd/tree/clang2 )

It is good for you ? (need to rebase)

**Comment by vincentbernat** [comment]
❦ 22 mai 2015 02:01 -0700, Alexis La Goutte <notifications@github.com> :

> I have make the change on clang2 branch (
> https://github.com/alagoutte/lldpd/tree/clang2 )
>
> It is good for you ? (need to rebase)

OK, that's small enough.

For interfaces-linux.c and priv-linux.c, I would rather enclose all
"linux/*" headers in the pragma: we don't really care about errors in
third-party headers.
-- 
Clothes make the man.  Naked people have little or no influence on society.
		-- Mark Twain

**Comment by alagoutte** [comment]
it will be good !

**Comment by vincentbernat** [comment]
Thanks!

**Pull request merged**
